steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wall-board/wall-board:$COMMIT_SHA', '.']
  
  # Docker 이미지를 Artifact Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wall-board/wall-board:$COMMIT_SHA']
  
  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'wall-board'
      - '--image=asia-northeast3-docker.pkg.dev/$PROJECT_ID/wall-board/wall-board:$COMMIT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/wall-board/wall-board:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY 